# Generated by Django 4.0.4 on 2022-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Tole bi 59', max_length=200),
        ),
    ]
