# Generated by Django 4.0.4 on 2022-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
