# Generated by Django 3.2.13 on 2022-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_tc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Заявка на сотрудничество', 'verbose_name_plural': 'Заявки на сотрудничество'},
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
