# Generated by Django 3.2.13 on 2022-05-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(default='', max_length=255, verbose_name='Номер дома')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField(default=0, verbose_name='Общая стоимость')),
                ('price_per_unit', models.FloatField(default=5000, verbose_name='Стоимость одного литра')),
                ('volume', models.FloatField(default=0, verbose_name='Объем')),
                ('payment_recieved', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('status', models.CharField(choices=[('Created', 'Создан'), ('Progress', 'В процессе'), ('Ready for shipping', 'Готов к доставке'), ('Shipping', 'Доставляется'), ('Done', 'Завершен'), ('Declined', 'Отклонен')], default='Created', max_length=255, verbose_name='Статус')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
