# Generated by Django 3.2.13 on 2022-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_recieved',
            new_name='payment_received',
        ),
        migrations.AlterField(
            model_name='config',
            name='price_per_unit',
            field=models.FloatField(default=5000, verbose_name='Стоимость литра сиропа (тг)'),
        ),
    ]
