# Generated by Django 3.2.13 on 2022-05-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=200.0, verbose_name='Объем котла')),
                ('engine_temperature', models.FloatField(default=17.0, verbose_name='Температура двигателя')),
                ('ending_time_of_iteration', models.DateTimeField(null=True, verbose_name='Конечное время выполнения нышней партии')),
                ('initial_order_volume', models.FloatField(null=True, verbose_name='Общий объем заказа')),
                ('made_volume', models.FloatField(null=True, verbose_name='Проделанный объем заказа')),
                ('engine_voltage', models.FloatField(null=True, verbose_name='PV')),
                ('engine_target_voltage', models.FloatField(null=True, verbose_name='SP')),
                ('error_prev', models.FloatField(null=True, verbose_name='Предыдущая ошибка')),
                ('coef_i', models.FloatField(default=0.0, verbose_name='Коэфициент I')),
                ('coef_mv_bar', models.FloatField(default=0.0, verbose_name='Коэфициент MV')),
                ('status', models.CharField(choices=[('VACANT', 'Готова к работе'), ('IN_PROGRESS', 'В процессе выполнения заказа'), ('DONE', 'Закончена работа над заказом'), ('ALARM', 'Перегрев двигателя')], default='VACANT', max_length=255, verbose_name='Статус')),
                ('mode', models.CharField(choices=[('AUTO', 'Автоматический режим'), ('MANUAL', 'Ручной режим')], default='MANUAL', max_length=255, verbose_name='Режим')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_performing', to='store.order', verbose_name='Выполняемый заказ')),
            ],
            options={
                'verbose_name': 'Котел',
                'verbose_name_plural': 'Котлы',
            },
        ),
    ]
