# Generated by Django 3.2.13 on 2022-05-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status'),
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_performing', to='store.order', verbose_name='Выполняемый заказ'),
        ),
    ]
